apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  namespace: icgroup
  labels:
    app: ic-webapp
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
        env: prod
    spec:
      containers:
        - name: ic-webapp
          image: titan111/ic-webapp:1.0
          ports:
            - containerPort: 8080
          env:
            - name: ODOO_URL
              value: "http://10.43.243.105:8069/web/login"
            - name: PGADMIN_URL
              value: "http://10.43.241.137:80"

