apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: icgroup
  labels:
    app: pgadmin
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
        env: prod
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@icgroup.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin123
          volumeMounts:
            - name: config-volume
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
      volumes:
        - name: config-volume
          configMap:
            name: pgadmin-config
