apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: icgroup
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30075
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  namespace: icgroup
spec:
  selector:
    app: odoo
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 30069
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ic-webapp-service
  namespace: icgroup
spec:
  selector:
    app: ic-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: icgroup
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
